# WalkLib Micro - Docker Compose with .env files
# Simple deployment using environment variables from .env file
version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@localhost:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  walklib-aisystem:
    image: buildingbite/walklib_aisystem:v1.2-secure
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - kafka

  walklib-user:
    image: buildingbite/walklib_user:latest
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-author:
    image: buildingbite/walklib_author:latest
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-book:
    image: buildingbite/walklib_book:latest
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-point:
    image: buildingbite/walklib_point:latest
    ports:
      - "8085:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-subscription:
    image: buildingbite/walklib_subscription:latest
    ports:
      - "8086:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-writing:
    image: buildingbite/walklib_writing:latest
    ports:
      - "8087:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka

  walklib-gateway:
    image: buildingbite/walklib_gateway:v1.1
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - walklib-aisystem
      - walklib-user
      - walklib-author
      - walklib-book
      - walklib-point
      - walklib-subscription
      - walklib-writing

  walklib-frontend:
    image: buildingbite/walklib_frontend:v1.1
    ports:
      - "80:80"
    depends_on:
      - walklib-gateway