apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-svc
spec:
  type: NodePort
  ports:
    - port: 8092 # 외부에서 접근할 포트
      targetPort: 8080 # 컨테이너 내부 포트
      nodePort: 30093
  selector:
    app: kafka-ui
  type: LoadBalancer
