name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./user management/pom.xml
          mvn clean package -f ./point management/pom.xml
          mvn clean package -f ./subscription management/pom.xml
          mvn clean package -f ./book management/pom.xml
          mvn clean package -f ./author management/pom.xml
          mvn clean package -f ./content writing management/pom.xml
          mvn clean package -f ./ai system management/pom.xml

      - name: Docker Build and push for UserManagement
        uses: docker/build-push-action@v4
        with:
          context: ./user management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user-management:latest
            ghcr.io/${{ github.repository }}/user-management:${{ github.ref_name }}
            
      - name: Docker Build and push for PointManagement
        uses: docker/build-push-action@v4
        with:
          context: ./point management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point-management:latest
            ghcr.io/${{ github.repository }}/point-management:${{ github.ref_name }}
            
      - name: Docker Build and push for SubscriptionManagement
        uses: docker/build-push-action@v4
        with:
          context: ./subscription management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/subscription-management:latest
            ghcr.io/${{ github.repository }}/subscription-management:${{ github.ref_name }}
            
      - name: Docker Build and push for BookManagement
        uses: docker/build-push-action@v4
        with:
          context: ./book management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/book-management:latest
            ghcr.io/${{ github.repository }}/book-management:${{ github.ref_name }}
            
      - name: Docker Build and push for AuthorManagement
        uses: docker/build-push-action@v4
        with:
          context: ./author management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/author-management:latest
            ghcr.io/${{ github.repository }}/author-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ContentWritingManagement
        uses: docker/build-push-action@v4
        with:
          context: ./content writing management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/content-writing-management:latest
            ghcr.io/${{ github.repository }}/content-writing-management:${{ github.ref_name }}
            
      - name: Docker Build and push for AiSystemManagement
        uses: docker/build-push-action@v4
        with:
          context: ./ai system management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/ai-system-management:latest
            ghcr.io/${{ github.repository }}/ai-system-management:${{ github.ref_name }}
            
