---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user management
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: point management
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, /pointLists/**
        - id: subscription management
          uri: http://localhost:8084
          predicates:
            - Path=/subscriptions/**, 
        - id: book management
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, /bookLists/**
        - id: author management
          uri: http://localhost:8086
          predicates:
            - Path=/authors/**, /authorManagements/**, /authorManagementViews/**
        - id: content writing management
          uri: http://localhost:8087
          predicates:
            - Path=/manuscripts/**, /manuscriptLists/**
        - id: ai system management
          uri: http://localhost:8089
          predicates:
            - Path=/ais/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8088

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user management
          uri: http://walklib_user_management:8080
          predicates:
            - Path=/users/**, 
        - id: point management
          uri: http://walklib_point_management:8080
          predicates:
            - Path=/points/**, 
        - id: subscription management
          uri: http://walklib_subscription_management:8080
          predicates:
            - Path=/subscriptions/**, 
        - id: book management
          uri: http://walklib_book_management:8080
          predicates:
            - Path=/books/**, 
        - id: author management
          uri: http://walklib_author_management:8080
          predicates:
            - Path=/authors/**, /authorManagements/**, 
        - id: content writing management
          uri: http://walklib_content_writing_management:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: ai system management
          uri: http://walklib_ai_system_management:8080
          predicates:
            - Path=/ais/**, 
        - id: frontend
          uri: http://walklib_frontend:80
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
