server:
  port: 8080

spring:
  application:
    name: gateway
  profiles: test
  cloud:
    gateway:
      routes:
        - id: user management
          uri: http://walklib_user_management:8080
          predicates:
            - Path=/users/**
        - id: test
          uri: http://httpbin.org
          predicates:
            - Path=/test/**