spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: user management
          uri: http://localhost:8082
          predicates:
            - Path=/users/**, 
        - id: point management
          uri: http://localhost:8083
          predicates:
            - Path=/points/**, /pointLists/**
        - id: subscription management
          uri: http://localhost:8084
          predicates:
            - Path=/subscriptions/**, 
        - id: book management
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, /bookLists/**
        - id: author management
          uri: http://localhost:8086
          predicates:
            - Path=/authors/**, /authorManagements/**, /authorManagementViews/**
        - id: content writing management
          uri: http://localhost:8087
          predicates:
            - Path=/manuscripts/**, /manuscriptLists/**
        - id: ai system management
          uri: http://localhost:8088
          predicates:
            - Path=/ais/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8088

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: user management
          uri: http://user:8080
          predicates:
            - Path=/users/**, 
        - id: point management
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: subscription management
          uri: http://subscription:8080
          predicates:
            - Path=/subscriptions/**, 
        - id: book management
          uri: http://book:8080
          predicates:
            - Path=/books/**, 
        - id: author management
          uri: http://author:8080
          predicates:
            - Path=/authors/**, /authorManagements/**, 
        - id: content writing management
          uri: http://content:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: ai system management
          uri: http://ai:8080
          predicates:
            - Path=/ais/**, 
        - id: frontend
          uri: http://frontend:80
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

---

spring:
  profiles: kubernetes
  cloud:
    gateway:
      routes:
        - id: user management
          uri: lb://user:8080
          predicates:
            - Path=/users/**, 
        - id: point management
          uri: lb://point:8080
          predicates:
            - Path=/points/**, 
        - id: subscription management
          uri: lb://subscription:8080
          predicates:
            - Path=/subscriptions/**, 
        - id: book management
          uri: lb://book:8080
          predicates:
            - Path=/books/**, 
        - id: author management
          uri: lb://author:8080
          predicates:
            - Path=/authors/**, /authorManagements/**, 
        - id: content writing management
          uri: lb://content:8080
          predicates:
            - Path=/manuscripts/**, 
        - id: ai system management
          uri: lb://ai:8080
          predicates:
            - Path=/ais/**, 
        - id: frontend
          uri: lb://frontend:80
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
