spring:
  profiles: docker
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user_management
          uri: http://walklib-user:8080
          predicates:
            - Path=/users/**
        - id: point_management
          uri: http://walklib-point:8080
          predicates:
            - Path=/points/**, /pointLists/**
        - id: subscription_management
          uri: http://walklib-subscription:8080
          predicates:
            - Path=/subscriptions/**
        - id: book_management
          uri: http://walklib-book:8080
          predicates:
            - Path=/books/**, /bookLists/**
        - id: author_management
          uri: http://walklib-author:8080
          predicates:
            - Path=/authors/**, /authorManagements/**, /authorManagementViews/**
        - id: content_writing_management
          uri: http://walklib-writing:8080
          predicates:
            - Path=/manuscripts/**, /manuscriptLists/**
        - id: ai_system_management
          uri: http://walklib-aisystem:8080
          predicates:
            - Path=/ai/**, /ais/**
        - id: frontend
          uri: http://walklib-frontend:80
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080