apiVersion: apps/v1
kind: Deployment
metadata:
  name: walklib-aisystem
  labels:
    app: ai-system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-system-management
  template:
    metadata:
      labels:
        app: ai-system-management
    spec:
      containers:
        - name: ai-system-management
          image: "buildingbite/walklib_aisystem:v1.3.0"
          env:
            - name: OPENAI_API_KEY
              value: "sk-dummy-key-for-testing-1234567890"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/ai/health'
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: '/ai/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
