apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-system-management
  labels:
    app: ai-system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-system-management
  template:
    metadata:
      labels:
        app: ai-system-management
    spec:
      containers:
        - name: ai-system-management
          image: "lmo2914/ai-m:latest"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
