# 클러스터 내부 및 외부 접근을 위한 서비스
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: NodePort # 외부 노출을 위해 NodePort 사용 (클라우드 환경에서는 LoadBalancer 사용 가능)
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 29092
      targetPort: 29092
      nodePort: 30092 # NodePort를 통해 외부에서 접근할 포트
  selector:
    app: kafka
---
# StatefulSet의 Pod들에게 고유 DNS를 부여하기 위한 헤드리스 서비스
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None # 헤드리스 서비스로 설정
  ports:
    - name: controller
      port: 29093
      targetPort: 29093
  selector:
    app: kafka
