# Build stage
FROM amazoncorretto:17-alpine AS build
RUN apk add --no-cache maven
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Runtime stage  
FROM amazoncorretto:17-alpine
COPY --from=build /build/target/*SNAPSHOT.jar app.jar
EXPOSE 8089
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["java","-Xmx400M","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar","--spring.profiles.active=docker"]
