apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: istio-system
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.istio-system.svc.cluster.local:3100
      editable: true
      jsonData:
        timeout: 60
        maxLines: 1000