---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: lmo2914/user-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: point-management
  labels:
    app: point-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: point-management
  template:
    metadata:
      labels:
        app: point-management
    spec:
      containers:
        - name: point-management
          image: lmo2914/point-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-management
  labels:
    app: subscription-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-management
  template:
    metadata:
      labels:
        app: subscription-management
    spec:
      containers:
        - name: subscription-management
          image: lmo2914/subs-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-management
  labels:
    app: book-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-management
  template:
    metadata:
      labels:
        app: book-management
    spec:
      containers:
        - name: book-management
          image: lmo2914/book-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-management
  labels:
    app: author-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-management
  template:
    metadata:
      labels:
        app: author-management
    spec:
      containers:
        - name: author-management
          image: lmo2914/author-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-writing-management
  labels:
    app: content-writing-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-writing-management
  template:
    metadata:
      labels:
        app: content-writing-management
    spec:
      containers:
        - name: content-writing-management
          image: lmo2914/content-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-system-management
  labels:
    app: ai-system-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-system-management
  template:
    metadata:
      labels:
        app: ai-system-management
    spec:
      containers:
        - name: ai-system-management
          image: lmo2914/ai-m:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-management


---


apiVersion: v1
kind: Service
metadata:
  name: point-management
  labels:
    app: point-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: point-management


---


apiVersion: v1
kind: Service
metadata:
  name: subscription-management
  labels:
    app: subscription-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: subscription-management


---


apiVersion: v1
kind: Service
metadata:
  name: book-management
  labels:
    app: book-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: book-management


---


apiVersion: v1
kind: Service
metadata:
  name: author-management
  labels:
    app: author-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: author-management


---


apiVersion: v1
kind: Service
metadata:
  name: content-writing-management
  labels:
    app: content-writing-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: content-writing-management


---


apiVersion: v1
kind: Service
metadata:
  name: ai-system-management
  labels:
    app: ai-system-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ai-system-management

