apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-management
  labels:
    app: content-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-management
  template:
    metadata:
      labels:
        app: content-management
    spec:
      containers:
        - name: content-management
          image: "walklib/content:v1.3.0"
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
