apiVersion: v1
kind: Service
metadata:
  name: content-writing-management
  labels:
    app: content-writing-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: content-writing-management